/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package janelas;

import execoes.ErroDeGravacaoException;
import execoes.ErroDeLeituraException;
import io.Carregador;
import io.Gravador;
import io.LeitorGravadorObj;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import operacoes.FiltroSexo;
import operacoes.removeAluno;

/**
 *
 * @author barbara
 */
public class CadastroAluno extends javax.swing.JFrame {

    private List<Aluno> alunos;

    /**
     * Creates new form cadastroAluno
     */
    public CadastroAluno() throws ErroDeLeituraException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) this.tAlunos.getModel();
        List<Aluno> alunos = Carregador.carregarAluno(new LeitorGravadorObj());
        if (alunos == null) {
            alunos = new ArrayList<Aluno>();
        }
        this.alunos = alunos;

        for (int i = 0; i < alunos.size(); i++) {
            String[] tabela = {alunos.get(i).getNome(), alunos.get(i).getSexo(), alunos.get(i).getCidade(), alunos.get(i).getEstado()};
            modelo.addRow(tabela);
        }
        tAlunos.setModel(modelo);

        /*this.alunos = (ObjAluno) Carregador.carregarDados(new LeitorGravadorObj(), "./dados/aluno.txt");
        if (alunos == null) {
            alunos = new ObjAluno();
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.tAlunos.getModel();
        for(int i = 0; i < alunos.getAlunos().size();i++){
            System.out.println(alunos.getAlunos().get(i).getNome());
        }
        this.tAlunos.setModel((TableModel) modelo);**/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoFiltro = new javax.swing.ButtonGroup();
        lCadastro = new javax.swing.JLabel();
        bNovoAluno = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lNomeFiltro = new javax.swing.JLabel();
        tNomeFiltro = new javax.swing.JTextField();
        lSexoFiltro = new javax.swing.JLabel();
        rFeminino = new javax.swing.JRadioButton();
        rMasculino = new javax.swing.JRadioButton();
        lCidadeFiltro = new javax.swing.JLabel();
        tCidadeFiltro = new javax.swing.JTextField();
        lEstadoFiltro = new javax.swing.JLabel();
        cEstadoFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlunos = new javax.swing.JTable();
        bEditar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        bSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        lCadastro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lCadastro.setText("Cadastro de Alunos");

        bNovoAluno.setText("Novo Aluno");
        bNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoAlunoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jPanel1.setToolTipText("");

        lNomeFiltro.setText("Nome");

        tNomeFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNomeFiltroKeyReleased(evt);
            }
        });

        lSexoFiltro.setText("Sexo");

        bgSexoFiltro.add(rFeminino);
        rFeminino.setText("Feminino");
        rFeminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rFemininoMousePressed(evt);
            }
        });

        bgSexoFiltro.add(rMasculino);
        rMasculino.setText("Masculino");
        rMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rMasculinoMousePressed(evt);
            }
        });

        lCidadeFiltro.setText("Cidade");

        tCidadeFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCidadeFiltroKeyReleased(evt);
            }
        });

        lEstadoFiltro.setText("Estado");

        cEstadoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cEstadoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEstadoFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNomeFiltro)
                    .addComponent(tNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rMasculino)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSexoFiltro)
                            .addComponent(rFeminino))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCidadeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCidadeFiltro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEstadoFiltro)
                            .addComponent(cEstadoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lNomeFiltro)
                        .addGap(12, 12, 12)
                        .addComponent(tNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSexoFiltro)
                            .addComponent(lCidadeFiltro)
                            .addComponent(lEstadoFiltro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rFeminino)
                            .addComponent(tCidadeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cEstadoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rMasculino)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAlunos);

        bEditar.setText("Editar");
        bEditar.setEnabled(false);
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bRemover.setText("Remover");
        bRemover.setEnabled(false);
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bNovoAluno))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCadastro)
                    .addComponent(bNovoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditar)
                    .addComponent(bRemover)
                    .addComponent(bSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoAlunoActionPerformed
        new Cadastro(alunos, this.tAlunos, "Cadastrar");
    }//GEN-LAST:event_bNovoAlunoActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void tNomeFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeFiltroKeyReleased
        DefaultTableModel modelo = (DefaultTableModel) this.tAlunos.getModel();
        modelo.setNumRows(0);

        for (Aluno aluno : alunos) {
            if (aluno.getNome().contains(tNomeFiltro.getText())) {
                String[] tabela = {aluno.getNome(), aluno.getSexo(), aluno.getCidade(), aluno.getEstado()};
                modelo.addRow(tabela);
            }
        }
        tAlunos.setModel(modelo);
    }//GEN-LAST:event_tNomeFiltroKeyReleased

    private void cEstadoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEstadoFiltroActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tAlunos.getModel();
        if (!"Todos".equals(cEstadoFiltro.getSelectedItem().toString())) {
            modelo.setNumRows(0);
            for (Aluno aluno : alunos) {

                if (aluno.getEstado().equals(cEstadoFiltro.getSelectedItem().toString())) {
                    String[] tabela = {aluno.getNome(), aluno.getSexo(), aluno.getCidade(), aluno.getEstado()};
                    modelo.addRow(tabela);
                }
            }
            tAlunos.setModel(modelo);
        } else {
            modelo.setNumRows(0);
            for (int i = 0; i < alunos.size(); i++) {
                String[] tabela = {alunos.get(i).getNome(), alunos.get(i).getSexo(), alunos.get(i).getCidade(), alunos.get(i).getEstado()};
                modelo.addRow(tabela);
            }
            tAlunos.setModel(modelo);
        }
    }//GEN-LAST:event_cEstadoFiltroActionPerformed

    private void tCidadeFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCidadeFiltroKeyReleased
        DefaultTableModel modelo = (DefaultTableModel) this.tAlunos.getModel();
        modelo.setNumRows(0);

        for (Aluno aluno : alunos) {
            if (aluno.getCidade().contains(tCidadeFiltro.getText())) {
                String[] tabela = {aluno.getNome(), aluno.getSexo(), aluno.getCidade(), aluno.getEstado()};
                modelo.addRow(tabela);
            }
        }
        tAlunos.setModel(modelo);
    }//GEN-LAST:event_tCidadeFiltroKeyReleased

    private void rFemininoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rFemininoMousePressed
        tAlunos.setModel(FiltroSexo.FiltroSexo(tAlunos, rFeminino, "Feminino", alunos));
    }//GEN-LAST:event_rFemininoMousePressed

    private void rMasculinoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMasculinoMousePressed
        tAlunos.setModel(FiltroSexo.FiltroSexo(tAlunos, rMasculino, "Masculino", alunos));
    }//GEN-LAST:event_rMasculinoMousePressed

    private void tAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAlunosMouseClicked
        if (tAlunos.getSelectedRow() != -1) {
            bEditar.setEnabled(true);
            bRemover.setEnabled(true);
        }
    }//GEN-LAST:event_tAlunosMouseClicked

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        DefaultTableModel remove = (DefaultTableModel) tAlunos.getModel();
        
        if (tAlunos.getSelectedRow() >= 0) {
            System.out.println(tAlunos.getValueAt(tAlunos.getSelectedRow(), 0).toString());
            int op = JOptionPane.showConfirmDialog(null, "Deseja Excluir Aluno?", "Alunos", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == op) {
                removeAluno.RemoveAluno(alunos, tAlunos.getValueAt(tAlunos.getSelectedRow(), 0).toString());
                remove.removeRow(tAlunos.getSelectedRow());
                tAlunos.setModel(remove);
            }
        }
        try {
            Gravador.gravarDados(new LeitorGravadorObj(), alunos);
        } catch (ErroDeGravacaoException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        bEditar.setEnabled(false);
        bRemover.setEnabled(false);
    }//GEN-LAST:event_bRemoverActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        List<Aluno> alunoN = new ArrayList<Aluno>();
        if (tAlunos.getSelectedRow() >= 0) {
            for (int i = 0; i < alunos.size(); i++) {
                if (tAlunos.getValueAt(tAlunos.getSelectedRow(), 0).equals(alunos.get(i).getNome())) {
                    String nome = alunos.get(i).getNome();
                    String endereco = alunos.get(i).getEndereco();
                    String cidade = alunos.get(i).getCidade();
                    String estado = alunos.get(i).getEstado();
                    String sexo = alunos.get(i).getSexo();
                    String obs = alunos.get(i).getObservacao();
                    ArrayList<String> disci = alunos.get(i).getInteresse();
                    Aluno novo = new Aluno(nome, endereco, estado, cidade, sexo, disci, obs);
                    alunoN.add(novo);
                    new Cadastro(alunoN, tAlunos, bEditar.getText());
                }
            }
        }
    }//GEN-LAST:event_bEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroAluno().setVisible(true);
                } catch (ErroDeLeituraException ex) {
                    Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bNovoAluno;
    private javax.swing.JButton bRemover;
    private javax.swing.JButton bSair;
    private javax.swing.ButtonGroup bgSexoFiltro;
    private javax.swing.JComboBox<String> cEstadoFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCadastro;
    private javax.swing.JLabel lCidadeFiltro;
    private javax.swing.JLabel lEstadoFiltro;
    private javax.swing.JLabel lNomeFiltro;
    private javax.swing.JLabel lSexoFiltro;
    private javax.swing.JRadioButton rFeminino;
    private javax.swing.JRadioButton rMasculino;
    private javax.swing.JTable tAlunos;
    private javax.swing.JTextField tCidadeFiltro;
    private javax.swing.JTextField tNomeFiltro;
    // End of variables declaration//GEN-END:variables
}
